language:
  - cpp

matrix:
  include:
    - os: linux
      dist: trusty

addons:
  apt:
    packages:
     - libbz2-dev libfftw3-dev libfishsound1-dev libid3tag0-dev liblo-dev liblrdf0-dev libmad0-dev liboggz2-dev libpulse-dev libsamplerate-dev libsndfile-dev libsord-dev libxml2-utils portaudio19-dev raptor-utils librubberband-dev autoconf libtool git mlton

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty
  - sudo apt-get update
  - sudo apt-get install qt510base qt510svg

before_script:
  - ls -lR /opt/qt510
  - /opt/qt510/bin/qmake

script:
  - make

after_script:
  - ./ci_test x

